services:
  postgres:
    image: postgres
    container_name: postgres_dressmanager
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER          = postgres
      - POSTGRES_PASSWORD      = postgres
      - POSTGRES_DB            = db_dressManager
      - POSTGRES_ROOT_PASSWORD = postgres